
name: gitleaks

on: [push,pull_request]

 
jobs:
  gitleaks:
       runs-on: ubuntu-latest
       steps:
        
         - run: mkdir -p /

         - run: echo hello > /world.txt

         - uses: actions/upload-artifact@v2
           with:
            name: my-artifact
            path: /world.txt
