name: gitleaks

on: [push,pull_request]

 
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: gitleaks-action
      uses: JTheinert/gitleaks-action@master
    - name: Gitleaks report
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
         name: gitleaks report
         path: gitleaks-report.json
    - name: Annotate
      uses: Attest/annotations-action@v1.0.7
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          input: 'gitleaks-report.json'
          title: 'Annotate Files'
