name: gitleaks

on: [push,pull_request]

 
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: create npmrc
      run: |
        touch ~/.npmrc 
        echo "//npm.pkg.github.com/:_authToken={githubtoken} \
        @attest:registry=https://npm.pkg.github.com/" >> ~/.npmrc
        cat ~/.npmrc
    - name: Annotate
      uses: Attest/annotations-action@v1.0.7
      with:
          token: ${{ secrets.ACTION_TOKEN }}
          input: gitleaks-report.json
          title: 'Annotate Files'
